### ISSUE TITLE
模型评估

### ISSUE THREAD

**Issue by with-him777** [opendatalab/PDF-Extract-Kit#10]
hi，想问一下 模型评估代码和对应的数据集可以提供吗

**Comment by wangbinDL** [comment]
评估代码@ouyanglinke 可以分享一下，数据集这里考虑到版权归属问题，仅用于内部测试。可以share几个demo对应的评测数据。

**Comment by wangbinDL** [comment]
@with-him777 
评测说明已更新，具体请参考：https://github.com/opendatalab/PDF-Extract-Kit/blob/main/assets/validation/README-zh_CN.md
