### ISSUE TITLE
离线部署paddleocr模型下载及存放地址

### ISSUE THREAD

**Issue by 724852499** [opendatalab/PDF-Extract-Kit#108]
离线部署时，paddleocr需要联网下载模型，自己离线下载放在指定位置（/root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_PP-OCRv4_det_infer.tar）还是不行，能请教下模型放哪个位置呢
![image](https://github.com/user-attachments/assets/9537911e-c75d-4d62-b9ad-8ef59b1acb99)

**Comment by myhloli** [comment]
要解压，你可以在另一台有网的机器下载，然后把整个.paddleocr目录拷贝过去

**Comment by 724852499** [comment]
感觉，用你说的方法可以运行了
