### ISSUE TITLE
运行pdf_extrct.py文件报paddlepaddle的异常

### ISSUE THREAD

**Issue by 19157681683** [opendatalab/PDF-Extract-Kit#12]
Error: Can not import paddle core while this file exists: /root/anaconda3/envs/pipeline/lib/python3.10/site-packages/paddle/base/libpaddle.so
Segmentation fault (core dumped)

请问考虑做个docker镜像嘛？

**Comment by myhloli** [comment]
有同事反馈过在ubuntu使用cpu版本的paddle 2.6.1有兼容问题，不知道您是否是这种情况，如果是的话可以尝试将paddlepaddle降级到2.5.2版本再试试。
