### ISSUE TITLE
About Layout detection SFT dataset

### ISSUE THREAD

**Issue by hjbiao09** [opendatalab/PDF-Extract-Kit#128]
Hi, first of all, thank you so much for releasing such a good source.

It works pretty well on our dataset, but we got incorrect layout detection in a few cases and want to further fine-tune the model with the layoutlmv3-sft pretrained model.
So, I would like to understand the format of the datasets used in the actual layout detection, could you please provide a link to the dataset source or related materials?

In `layoutlmv3_base_inference.yaml`, the relevant dataset entry is `publaynet/layout_scihub`, did you train with that dataset?

Again, thanks for opening up your good source.

**Comment by ouyanglinke** [comment]
Layoutlmv3 take COCO format data as input during the sft process in object detection. We use our own datasets for SFT, which would not be open-source. You can build your own sft dataset for your specific cases. Or you could provide those bad cases to us for further sft training. We will update our model once we collect enough bad cases.

**Comment by hjbiao09** [comment]
Hi,

Thank you for providing the information regarding the dataset. With your help, we were able to resolve the issue, and I will close this issue now.

Once again, thank you for releasing such a great resource.
