### ISSUE TITLE
需要多少显存？

### ISSUE THREAD

**Issue by zqyz333** [opendatalab/PDF-Extract-Kit#13]
我看直播演示的时候是1660Ti显卡，可以跑但是速度比较慢，我也是1660Ti的显卡，一跑就爆显存了，需要哪里设置一下吗？

**Comment by myhloli** [comment]
确认显卡显存是否够用，最低6GB，推荐16GB及以上
如果显存小于16GB，请将预处理中需要修改的配置中batch_size酌情调低至"64"或"32"

**Comment by myhloli** [comment]
@zqyz333 在整合模型pipeline的mineru中，我们降低了默认的batchsize参数，并把整本处理逻辑改为分页处理，降低了一些显存和内存的空间要求，对6G显存设备理论可以更友好一些。如果您可以把有问题的pdf文件共享给我们用来测试那就再好不过了。

**Comment by zqyz333** [comment]
谢谢，我是项目下另一个工具extract-PDF爆了显存，后来用CPU版本跑成功，用MinerU建立markdown时没有爆显存。

**Comment by myhloli** [comment]
> 谢谢，我是项目下另一个工具extract-PDF爆了显存，后来用CPU版本跑成功，用MinerU建立markdown时没有爆显存。

好的，感谢反馈
