### ISSUE TITLE
使用cpu运行报错fairscale模块问题

### ISSUE THREAD

**Issue by yang123456he** [opendatalab/PDF-Extract-Kit#132]
(pipeline) PS C:\Users\杨贺\Desktop\PDF-Extract-Kit-main> pip uninstall fairscale
Found existing installation: fairscale 0.4.13
Uninstalling fairscale-0.4.13:
  Would remove:
    d:\anaconda\envs\pipeline\lib\site-packages\fairscale-0.4.13.dist-info\*
    d:\anaconda\envs\pipeline\scripts\wgit.exe
Proceed (Y/n)? Y
  Successfully uninstalled fairscale-0.4.13
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting fairscale
  Using cached fairscale-0.4.13-py3-none-any.whl
Requirement already satisfied: torch>=1.8.0 in d:\anaconda\envs\pipeline\lib\site-packages (from fairscale) (2.3.1)
Requirement already satisfied: numpy>=1.22.0 in d:\anaconda\envs\pipeline\lib\site-packages (from fairscale) (1.26.4)
Requirement already satisfied: filelock in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (4.12.2)
Requirement already satisfied: sympy in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (1.13.3)
Requirement already satisfied: networkx in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (3.3)
Requirement already satisfied: jinja2 in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (3.1.4)
Requirement already satisfied: fsspec in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (2024.6.1)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in d:\anaconda\envs\pipeline\lib\site-packages (from torch>=1.8.0->fairscale) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in d:\anaconda\envs\pipeline\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.8.0->fairscale) (2021.4.0)
Requirement already satisfied: tbb==2021.* in d:\anaconda\envs\pipeline\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.8.0->fairscale) (2021.13.1)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda\envs\pipeline\lib\site-packages (from jinja2->torch>=1.8.0->fairscale) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\anaconda\envs\pipeline\lib\site-packages (from sympy->torch>=1.8.0->fairscale) (1.3.0)
Installing collected packages: fairscale
Successfully installed fairscale-0.4.13
(pipeline) PS C:\Users\杨贺\Desktop\PDF-Extract-Kit-main> python pdf_extract.py --pdf .\input\002.pdf
Traceback (most recent call last):
  File "C:\Users\杨贺\Desktop\PDF-Extract-Kit-main\pdf_extract.py", line 19, in <module>
    from unimernet.common.config import Config
  File "D:\anaconda\envs\pipeline\lib\site-packages\unimernet\__init__.py", line 16, in <module>
    from unimernet.models import *
  File "D:\anaconda\envs\pipeline\lib\site-packages\unimernet\models\__init__.py", line 16, in <module>
    from unimernet.models.unimernet.unimernet import UniMERModel
  File "D:\anaconda\envs\pipeline\lib\site-packages\unimernet\models\unimernet\unimernet.py", line 4, in <module>
    from unimernet.models.blip2_models.blip2 import Blip2Base
  File "D:\anaconda\envs\pipeline\lib\site-packages\unimernet\models\blip2_models\blip2.py", line 26, in <module>
    from unimernet.models.clip_vit import create_clip_vit_L
  File "D:\anaconda\envs\pipeline\lib\site-packages\unimernet\models\clip_vit.py", line 10, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
ModuleNotFoundError: No module named 'fairscale'

**Comment by Kami-prog** [comment]
install this
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by emadellaloggia** [comment]
I think this will help you.
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by yang123456he** [comment]
我使用的python
