### ISSUE TITLE
Collab notebook has old magic-pdf command

### ISSUE THREAD

**Issue by chrislatimer** [opendatalab/PDF-Extract-Kit#139]
The collab notebook example has a command that is no longer supported in magic-pdf:

```
!echo "{}" > ~/magic-pdf.json

!magic-pdf pdf-command --pdf "1706.03762.pdf" --model "output/1706.03762.json"
```

I tried to track down the equivalent command in the magic-pdf but I couldn't find it and ended up downgrading to 0.6.1 to get around the issue. The PDF location is now `-p` but I didn't see an equivalent for `--model`.

**Comment by myhloli** [comment]
The new version of magic-pdf only requires inputting a PDF file to complete the parsing task. Specific examples can be found at https://colab.research.google.com/gist/papayalove/b5f4913389e7ff9883c6b687de156e78/mineru_demo.ipynb.
