### ISSUE TITLE
ERROR: detectron2-0.6-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by lpy148145** [opendatalab/PDF-Extract-Kit#143]
ERROR: detectron2-0.6-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by myhloli** [comment]
The precompiled version does not support ARM Linux. You can try building it yourself from the source code repository: https://github.com/facebookresearch/detectron2

**Comment by lpy148145** [comment]
thanks   File "/root/extract-pdf/PDF-Extract-Kit-main/pdf_extract.py", line 2, in <module>
    import cv2
  File "/root/miniconda3/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/miniconda3/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by lpy148145** [comment]
把项目拉下来，也不可以吗

**Comment by myhloli** [comment]
>ImportError: libGL.so.1: cannot open shared object file: No such file or directory

sudo apt install libgl1-mesa-glx

**Comment by lpy148145** [comment]
(base) [root@c1fcfa1c0161 PDF-Extract-Kit-main]# yum install libgl1-mesa-glx
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
No package libgl1-mesa-glx available.

**Comment by lpy148145** [comment]
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
Traceback (most recent call last):
  File "/root/extract-pdf/PDF-Extract-Kit-main/pdf_extract.py", line 2, in <module>
    import cv2
  File "/root/miniconda3/lib/python3.12/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/miniconda3/lib/python3.12/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import

**Comment by lpy148145** [comment]
是numpy的版本不对么 就是按照文件安装的依赖

**Comment by myhloli** [comment]
有个简单的方案，先conda 创建一个python3.10的环境，再装下面这个依赖包
https://huggingface.co/spaces/opendatalab/MinerU/blob/main/requirements.txt
装完之后再pip install unimernet==0.1.6 
这样环境就不会有问题。
