### ISSUE TITLE
layoutlmv3版面分析微调问题

### ISSUE THREAD

**Issue by Frank-Zeng** [opendatalab/PDF-Extract-Kit#151]
参考微软官方layoutlmv3的detection进行版面检测sft微调(https://github.com/microsoft/unilm/layoutlmv3/examples/object_detection)，发现标注结果会出现如下这种detection边框会重叠，同样代码原始未微调版本未出现这种情况，请问出现这种的原因可能是啥？
![image](https://github.com/user-attachments/assets/58e0ae5c-136a-425e-b91f-24bc39f557dc)

**Comment by JulioZhao97** [comment]
您好，麻烦问一下您这边有原始图片吗，我这里测试一下
