### ISSUE TITLE
版面分析模型doclayout_yolo_ft，识别图片footnote错误

### ISSUE THREAD

**Issue by dalinautoagents** [opendatalab/PDF-Extract-Kit#155]
![Uploading 1729298392969.jpg…]()

**Comment by dalinautoagents** [comment]
![Uploading 1729298392969.jpg…]()

**Comment by JulioZhao97** [comment]
您好，我这里没有看到图片，可以重新上传一下吗？

**Comment by dalinautoagents** [comment]
[image]

**Comment by dalinautoagents** [comment]
![1729298392969](https://github.com/user-attachments/assets/83d4ae45-b951-4c2b-a638-326d928c9b8f)

**Comment by JulioZhao97** [comment]
感谢反馈，我们后续会对模型这个问题进行优化，另外请问能否提供原始图片或者PDF文件以便测试？

**Comment by JulioZhao97** [comment]
感谢反馈
