### ISSUE TITLE
layout 识别不准，出现了遗漏的现象

### ISSUE THREAD

**Issue by alpha4501** [opendatalab/PDF-Extract-Kit#159]
layout model: doclayout_yolo
![WechatIMG17](https://github.com/user-attachments/assets/b68faf82-e2c2-49b9-acef-14d3af657818)

layout model: layoutlmv3
![Uploading WechatIMG13.jpg…]()

**Comment by JulioZhao97** [comment]
您好，目前通过测试我们也发现了这个问题，DocLayout-YOLO可能因为模型过小（LayoutLMv3的十分之一）可能会出现此类特征不足导致的问题，可以麻烦您提供原始的文档或者图片以供分析吗，感谢反馈！
