### ISSUE TITLE
请问config.json在哪里

### ISSUE THREAD

**Issue by luciaganlulu** [opendatalab/PDF-Extract-Kit#162]
您好，我根据[这个教程](https://pdf-extract-kit.readthedocs.io/en/latest/algorithm/layout_detection.html)正在尝试使用layoutlmv3-ft进行demo数据推理，完全按照里面的操作了，里面的`model_path`改成了`models/Layout/LayoutLMv3/model_final.pth`（模型也实际这样放的），执行`python scripts/layout_detection.py --config configs/layout_detection.yaml` 报错如下

> OSError: models/Layout/LayoutLMv3/ does not appear to have a file named config.json. Checkout 'https://huggingface.co/models/Layout/LayoutLMv3/
/tree/None' for available files.

请问这个config.json是在哪里呢？是文件问题还是我的环境有问题呢？这个环境先后安装了三个项目的依赖，分别是[GOT-OCR2.0](https://github.com/Ucas-HaoranWei/GOT-OCR2.0/tree/main)，[DocLayout-YOLO](https://github.com/opendatalab/DocLayout-YOLO)，[PDF-Extract-Kit](https://github.com/opendatalab/PDF-Extract-Kit)

**Comment by JulioZhao97** [comment]
您好，可以看一下您的config配置文件吗，```models/Layout/LayoutLMv3```下需要有```config.json```，model可以在这里下载：
![截屏2024-10-24 20 54 45](https://github.com/user-attachments/assets/7ecb837b-7e3b-4489-a2dd-eab383e80d64)

**Comment by luciaganlulu** [comment]
> 您好，可以看一下您的config配置文件吗，`models/Layout/LayoutLMv3`下需要有`config.json`，model可以在这里下载： ![截屏2024-10-24 20 54 45](https://private-user-images.githubusercontent.com/40555727/379776286-7ecb837b-7e3b-4489-a2dd-eab383e80d64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NzQ4MzQsIm5iZiI6MTcyOTc3NDUzNCwicGF0aCI6Ii80MDU1NTcyNy8zNzk3NzYyODYtN2VjYjgzN2ItN2UzYi00NDg5LWEyZGQtZWFiMzgzZTgwZDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDEyNTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMTJlMTk2ZDY1ODNhZTU3OTE5M2JjMzU5Y2YwMmE2Mjg0MzJlYjE1NDhkYmNlMDViNjIzMGVkODc2MmQ4YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RhF9NIKvJjjzWOuVfTlIsUbOQqAtlbZT29mB5JECIH4)

哦哦，我只下载了.pth，没下载这个config.json，不好意思是我的问题，我根据[这里](https://pdf-extract-kit.readthedocs.io/en/latest/algorithm/layout_detection.html)弄的没看到config.json这个
