### ISSUE TITLE
获取layoutlmv3-ft的版面检测推理结果

### ISSUE THREAD

**Issue by luciaganlulu** [opendatalab/PDF-Extract-Kit#163]
您好，直接运行`python scripts/layout_detection.py --config configs/layout_detection.yaml`的话，只是新建了`result_path`路径，并没有存储`detection_results`结果，请问如何解析出其中的`im_path, boxes, scores, classes`信息呢？检测结果`annotated_image`在哪里呢？

**Comment by JulioZhao97** [comment]
您好，
1. 可视化结果，config文件里需要设置```visualize=True```
2. 推理结果例如```bbox, class, score```等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61

**Comment by luciaganlulu** [comment]
> 您好，
> 
> 1. 可视化结果，config文件里需要设置`visualize=True`
> 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61

请问config文件是跟`model_final.pth`一起的那个`config.json`么？里面没有`visualize`，只有个`visual_embed`

**Comment by luciaganlulu** [comment]
> 您好，
> 
> 1. 可视化结果，config文件里需要设置`visualize=True`
> 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61

请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？

**Comment by JulioZhao97** [comment]
> > 您好，
> > 
> > 1. 可视化结果，config文件里需要设置`visualize=True`
> > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> 
> 请问config文件是跟`model_final.pth`一起的那个`config.json`么？里面没有`visualize`，只有个`visual_embed`

不是，是```configs/layout_detection_layoutlmv3.yaml```里面需要设置```visualize=True```

**Comment by JulioZhao97** [comment]
> > 您好，
> > 
> > 1. 可视化结果，config文件里需要设置`visualize=True`
> > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> 
> 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？

是的，您可以通过切换到```predict_pdf```来处理PDF文件

**Comment by luciaganlulu** [comment]
> > > 您好，
> > > 
> > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > 
> > 
> > 请问config文件是跟`model_final.pth`一起的那个`config.json`么？里面没有`visualize`，只有个`visual_embed`
> 
> 不是，是`configs/layout_detection_layoutlmv3.yaml`里面需要设置`visualize=True`

您好，我这样设置 `visualize=True`，执行 `python scripts/layout_detection.py --config configs/layout_detection.yaml`后， `outputs/layout_detection` 里面还是空的，请问是没有保存成功嘛？
![image](https://github.com/user-attachments/assets/d44e0970-1229-4ea5-980d-fe69ba3604b1)

**Comment by luciaganlulu** [comment]
> > > 您好，
> > > 
> > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > 
> > 
> > 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？
> 
> 是的，您可以通过切换到`predict_pdf`来处理PDF文件

您好，这里我有点没懂，为什么突然说起 `predict_pdf`呢？当我像现在这样用 `predict_image` 的话，[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是不是 [这个results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 直接传参过来的呢？因为前者代码里我没法找到上层函数定义，好像写的有点隐蔽，跳转找不到 ～

**Comment by JulioZhao97** [comment]
> > > > 您好，
> > > > 
> > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > 
> > > 
> > > 请问config文件是跟`model_final.pth`一起的那个`config.json`么？里面没有`visualize`，只有个`visual_embed`
> > 
> > 
> > 不是，是`configs/layout_detection_layoutlmv3.yaml`里面需要设置`visualize=True`
> 
> 您好，我这样设置 `visualize=True`，执行 `python scripts/layout_detection.py --config configs/layout_detection.yaml`后， `outputs/layout_detection` 里面还是空的，请问是没有保存成功嘛？ ![image](https://private-user-images.githubusercontent.com/178551404/380021236-d44e0970-1229-4ea5-980d-fe69ba3604b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzM5NDMsIm5iZiI6MTcyOTgzMzY0MywicGF0aCI6Ii8xNzg1NTE0MDQvMzgwMDIxMjM2LWQ0NGUwOTcwLTEyMjktNGVhNS05ODBkLWZlNjliYTM2MDRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNTIwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWExYWNkZjJhN2QzMzE3NDA4MzM1MWMxYTJmMDMwYWVhY2ZhODIzYTEzM2UxYTVhM2JiOTk0NTM2M2FjOTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FRYz7JJDs4jxp9r6hIwiRdylsqHRR8mf_DlJyWoT6-E)

您好，这里```visualize=True```的缩进不对，```visualize```是```model_config```下的参数

**Comment by luciaganlulu** [comment]
> > > > > 您好，
> > > > > 
> > > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > > 
> > > > 
> > > > 请问config文件是跟`model_final.pth`一起的那个`config.json`么？里面没有`visualize`，只有个`visual_embed`
> > > 
> > > 
> > > 不是，是`configs/layout_detection_layoutlmv3.yaml`里面需要设置`visualize=True`
> > 
> > 
> > 您好，我这样设置 `visualize=True`，执行 `python scripts/layout_detection.py --config configs/layout_detection.yaml`后， `outputs/layout_detection` 里面还是空的，请问是没有保存成功嘛？ ![image](https://private-user-images.githubusercontent.com/178551404/380021236-d44e0970-1229-4ea5-980d-fe69ba3604b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzM5NDMsIm5iZiI6MTcyOTgzMzY0MywicGF0aCI6Ii8xNzg1NTE0MDQvMzgwMDIxMjM2LWQ0NGUwOTcwLTEyMjktNGVhNS05ODBkLWZlNjliYTM2MDRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNTIwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWExYWNkZjJhN2QzMzE3NDA4MzM1MWMxYTJmMDMwYWVhY2ZhODIzYTEzM2UxYTVhM2JiOTk0NTM2M2FjOTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FRYz7JJDs4jxp9r6hIwiRdylsqHRR8mf_DlJyWoT6-E)
> 
> 您好，这里`visualize=True`的缩进不对，`visualize`是`model_config`下的参数

好的好的可以啦，感谢感谢～

**Comment by luciaganlulu** [comment]
> > > > 您好，
> > > > 
> > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > 
> > > 
> > > 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？
> > 
> > 
> > 是的，您可以通过切换到`predict_pdf`来处理PDF文件
> 
> 您好，这里我有点没懂，为什么突然说起 `predict_pdf`呢？当我像现在这样用 `predict_image` 的话，[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是不是 [这个results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 直接传参过来的呢？因为前者代码里我没法找到上层函数定义，好像写的有点隐蔽，跳转找不到 ～

这个我测试了一下，这两个是一模一样的，我理解的对嘛？

**Comment by JulioZhao97** [comment]
> > > > > 您好，
> > > > > 
> > > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > > 
> > > > 
> > > > 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？
> > > 
> > > 
> > > 是的，您可以通过切换到`predict_pdf`来处理PDF文件
> > 
> > 
> > 您好，这里我有点没懂，为什么突然说起 `predict_pdf`呢？当我像现在这样用 `predict_image` 的话，[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是不是 [这个results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 直接传参过来的呢？因为前者代码里我没法找到上层函数定义，好像写的有点隐蔽，跳转找不到 ～
> 
> 这个我测试了一下，这两个是一模一样的，我理解的对嘛？

这两个函数虽然都是准备好input，然后调用推理，但是传入的input类型不一样，如果您传入的input是一系列或者单个PDF，需要调用```predict_pdf```，如果是图片的话需要调用```predict_images```

**Comment by luciaganlulu** [comment]
> > > > > > 您好，
> > > > > > 
> > > > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > > > 
> > > > > 
> > > > > 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？
> > > > 
> > > > 
> > > > 是的，您可以通过切换到`predict_pdf`来处理PDF文件
> > > 
> > > 
> > > 您好，这里我有点没懂，为什么突然说起 `predict_pdf`呢？当我像现在这样用 `predict_image` 的话，[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是不是 [这个results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 直接传参过来的呢？因为前者代码里我没法找到上层函数定义，好像写的有点隐蔽，跳转找不到 ～
> > 
> > 
> > 这个我测试了一下，这两个是一模一样的，我理解的对嘛？
> 
> 这两个函数虽然都是准备好input，然后调用推理，但是传入的input类型不一样，如果您传入的input是一系列或者单个PDF，需要调用`predict_pdf`，如果是图片的话需要调用`predict_images`

嗯嗯，明白了，那就是输入不同使用的函数不同，`predict_pdf`和`predict_images`这两个函数本质都是调用的predict那个函数，前两者只能接受单一类型输入，后者可以接受多种类型输入，我理解对嘛？

**Comment by JulioZhao97** [comment]
> > > > > > > 您好，
> > > > > > > 
> > > > > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > > > > 
> > > > > > 
> > > > > > 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？
> > > > > 
> > > > > 
> > > > > 是的，您可以通过切换到`predict_pdf`来处理PDF文件
> > > > 
> > > > 
> > > > 您好，这里我有点没懂，为什么突然说起 `predict_pdf`呢？当我像现在这样用 `predict_image` 的话，[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是不是 [这个results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 直接传参过来的呢？因为前者代码里我没法找到上层函数定义，好像写的有点隐蔽，跳转找不到 ～
> > > 
> > > 
> > > 这个我测试了一下，这两个是一模一样的，我理解的对嘛？
> > 
> > 
> > 这两个函数虽然都是准备好input，然后调用推理，但是传入的input类型不一样，如果您传入的input是一系列或者单个PDF，需要调用`predict_pdf`，如果是图片的话需要调用`predict_images`
> 
> 嗯嗯，明白了，那就是输入不同使用的函数不同，`predict_pdf`和`predict_images`这两个函数本质都是调用的predict那个函数，前两者只能接受单一类型输入，后者可以接受多种类型输入，我理解对嘛？

是的，如果您传入的是PDF请使用```predict_pdf```，如果传入的是图像请使用```predict_images```

**Comment by luciaganlulu** [comment]
> > > > > > > > 您好，
> > > > > > > > 
> > > > > > > > 1. 可视化结果，config文件里需要设置`visualize=True`
> > > > > > > > 2. 推理结果例如`bbox, class, score`等在https://github.com/opendatalab/PDF-Extract-Kit/blob/710f577f308f3604e4450076fc04392d2d11009f/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L59-L61
> > > > > > > 
> > > > > > > 
> > > > > > > 请问下[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是[这里的results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 嘛？
> > > > > > 
> > > > > > 
> > > > > > 是的，您可以通过切换到`predict_pdf`来处理PDF文件
> > > > > 
> > > > > 
> > > > > 您好，这里我有点没懂，为什么突然说起 `predict_pdf`呢？当我像现在这样用 `predict_image` 的话，[这个detection_results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/scripts/layout_detection.py#L30) 是不是 [这个results](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/pdf_extract_kit/tasks/layout_detection/models/layoutlmv3.py#L81) 直接传参过来的呢？因为前者代码里我没法找到上层函数定义，好像写的有点隐蔽，跳转找不到 ～
> > > > 
> > > > 
> > > > 这个我测试了一下，这两个是一模一样的，我理解的对嘛？
> > > 
> > > 
> > > 这两个函数虽然都是准备好input，然后调用推理，但是传入的input类型不一样，如果您传入的input是一系列或者单个PDF，需要调用`predict_pdf`，如果是图片的话需要调用`predict_images`
> > 
> > 
> > 嗯嗯，明白了，那就是输入不同使用的函数不同，`predict_pdf`和`predict_images`这两个函数本质都是调用的predict那个函数，前两者只能接受单一类型输入，后者可以接受多种类型输入，我理解对嘛？
> 
> 是的，如果您传入的是PDF请使用`predict_pdf`，如果传入的是图像请使用`predict_images`

好的明白了感谢您的耐心解答，非常感谢！

**Comment by luciaganlulu** [comment]
您好，请问当多个图片在不同路径的情况下如何推理呢？目前好像必须把所有图片直接放在`configs/layout_detection.yaml`中`inputs`这个路径下面。能否可以像`DocLayout-YOLO`那样支持image_path_lists输入呢？

**Comment by JulioZhao97** [comment]
您好，目前是不支持的，但是您可以自行修改代码，目前代码的逻辑是将输入路径转换成```List[PIL.Images]```再逐个传入```layoutlmv3```进行推理

**Comment by luciaganlulu** [comment]
> 您好，目前是不支持的，但是您可以自行修改代码，目前代码的逻辑是将输入路径转换成`List[PIL.Images]`再逐个传入`layoutlmv3`进行推理

好的非常感谢～ 已经把layoutlmv3-ft单独拎出来，输入一个图片获取一个检测结果，只是这样就不能利用visualize=True获取annotated_image，需要自己画这个～
