### ISSUE TITLE
layoutlmv3-ft推理设置batchsize为大于1的数字

### ISSUE THREAD

**Issue by luciaganlulu** [opendatalab/PDF-Extract-Kit#165]
您好，请问支持`batchsize`为大于`1`的数字么？我目前执行的是`predict_images`函数，用的`scripts/layout_detection.py`

**Comment by JulioZhao97** [comment]
您好，现在是不支持的，由于模型太大，layoutlmv3-ft在batch-size=8很不稳定，同时batch-size>1没有明显显著的加速
