### ISSUE TITLE
运行OCR脚本错误

### ISSUE THREAD

**Issue by YuanZheng612** [opendatalab/PDF-Extract-Kit#178]
配完环境后，测试了布局监测，可以运行，在测试ocr的时候运行脚本之后报如下错误。该如何解决？
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle_infer::Tensor::CopyFromCpu<float>(float const*)
1   std::__basic_future<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >::_M_get_result() const
2   std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool, int), phi::Place, bool, int> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >::_M_complete_async()
3   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool, int), phi::Place, bool, int> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
5   std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > paddle::platform::CreateDeviceContext<phi::GPUContext>(phi::Place const&, bool, int)
6   std::enable_if<std::is_same<phi::GPUContext, phi::GPUContext>::value, phi::GPUContext*>::type paddle::platform::ConstructDevCtx<phi::GPUContext>(phi::Place const&, int)
7   phi::GPUContext::GPUContext(phi::GPUPlace const&, bool, int)
8   phi::InitGpuProperties(phi::Place, int*, int*, int*, int*, int*, int*, std::array<int, 3ul>*)
9   cudnnGetVersion

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1732178124 (unix time) try "date -d @1732178124" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000600ad) received by PID 393389 (TID 0x7e36af256740) from PID 393389 ***]

Aborted (core dumped)

**Comment by wufan-tb** [comment]
看起来是你的平台不支持paddlegpu加速，直接跑paddleocr应该也跑不通，可以试试cpu版本的paddle

**Comment by YuanZheng612** [comment]
> 看起来是你的平台不支持paddlegpu加速，直接跑paddleocr应该也跑不通，可以试试cpu版本的paddle

好的，感谢回复
