### ISSUE TITLE
Order of bboxes and detected class abandon

### ISSUE THREAD

**Issue by allthatido** [opendatalab/PDF-Extract-Kit#180]
Hello

names: {0: 'title', 1: 'plain text', 2: 'abandon', 3: 'figure', 4: 'figure_caption', 5: 'table', 6: 'table_caption', 7: 'table_footnote', 8: 'isolate_formula', 9: 'formula_caption'}

What does 2: 'abandon' mean ?

Also is there a way i can get the order of the detected bboxes ?

Thanks

**Comment by JulioZhao97** [comment]
Thanks for you interest on our work:
1. abandon refers to ```Includes headers, footers, page numbers, page footnotes, and marginal notes.```, for more details, you can refer to [DocLayout-YOLO paper](https://arxiv.org/abs/2410.12628)
2. To sort detected bboxes, you can refer to [MinerU](https://github.com/opendatalab/MinerU), which supports reading order prediction now.

**Comment by allthatido** [comment]
Thanks for your response. Can you point to the relevant code in MinerU where reading order detection is implemented.

thanks

**Comment by JulioZhao97** [comment]
@allthatido That I don't really know, sorry, you can raise an issue in thier repo

**Comment by allthatido** [comment]
Thank you for your response and great work.
