### ISSUE TITLE
关于layout模型的微调

### ISSUE THREAD

**Issue by flow3rdown** [opendatalab/PDF-Extract-Kit#189]
您好，目前使用的DocLayout-YOLO模型作为Layout模型，想对此进行进一步的微调，有几个疑问想请教一下：
1. 请问PDF-Extract-Kit中提供的layout模型的权重[doclayout_yolo_ft.pt](https://huggingface.co/opendatalab/PDF-Extract-Kit-1.0/blob/main/models/Layout/YOLO/doclayout_yolo_ft.pt)是自己单独训练的吗？如果想微调话可以基于DocLayout-YOLO提供的代码进行微调吗？但似乎无法直接读入这个模型权重；
2. 对于数据方法您有什么好的建议吗？可以基于mesh-candidate_bestfit 方法进行生成吗？

感觉各位大佬，期待回复。

**Comment by JulioZhao97** [comment]
相关讨论见：https://github.com/opendatalab/DocLayout-YOLO/issues/58
