### ISSUE TITLE
最好能够提供一个在线访问体验的demo地址

### ISSUE THREAD

**Issue by faceAngus** [opendatalab/PDF-Extract-Kit#22]
直接安装整个环境，对很多人来说是一件麻烦的事情，特别对新手来说。
看过很多开源的文档解析，他们都会提供一个在线访问的地址，来体验解析的效果。这会很友好。

**Comment by wangbinDL** [comment]
谢谢建议，目前我们在排期，在线访问版本会有的，敬请期待~

**Comment by freedom1993** [comment]
跪求，这个啥时候能提供出来

**Comment by wangbinDL** [comment]
@freedom1993 下周

**Comment by xxlxms** [comment]
+1

**Comment by xiaohaoge15** [comment]
在线体验地址有了么

**Comment by drunkpig** [comment]
@xiaohaoge15 https://datalab.staging.openxlab.org.cn/OpenSourceTools/Extractor

**Comment by drunkpig** [comment]
@freedom1993 @faceAngus @xxlxms https://datalab.staging.openxlab.org.cn/OpenSourceTools/Extractor

**Comment by xiaohaoge15** [comment]
> @xiaohaoge15 https://datalab.staging.openxlab.org.cn/OpenSourceTools/Extractor

链接打不开

**Comment by myhloli** [comment]
> 链接好像打不开

https://opendatalab.com/OpenSourceTools/Extractor/PDF

这个
