### ISSUE TITLE
公式生成重复

### ISSUE THREAD

**Issue by dt-yy** [opendatalab/PDF-Extract-Kit#25]
![image](https://github.com/user-attachments/assets/adbbb1fd-51bd-4e28-92ae-8ad520b2cca5)

**Comment by wangbinDL** [comment]
原始文件可以发下

**Comment by dt-yy** [comment]
<img width="255" alt="企业微信截图_17213870047857" src="https://github.com/user-attachments/assets/7e3b6465-0a7e-4009-abc0-a85ee11b828c">

**Comment by wangbinDL** [comment]
<img width="1466" alt="image" src="https://github.com/user-attachments/assets/6faf5fc9-48be-4cdf-a52e-beb34c1db2bd">

Thank you for reporting this issue. I have tested the image and the recognition results appear to be correct. Here are a few suggestions:
1. Please try setting up a fresh environment with conda.
2. Verify that the model has been downloaded completely and correctly. You can use the following MD5 checksums to verify the integrity of your files:
```bash
ccd349f431879e7a7675fc10ca32e1fa  pytorch_model.bin  
351652071425d3d36a634ccc8efb22e8  tokenizer.json  
97f4867b4ff4e9a96c8daba8aaa793b4  tokenizer_config.json  
```

If the problem persists, please provide more details about your setup and the image used for testing.
