### ISSUE TITLE
layoutlm的config中vocab_size含义

### ISSUE THREAD

**Issue by ai1361720220000** [opendatalab/PDF-Extract-Kit#26]
请问一下用layoutlmv3做目标检测，我看yaml里设置IMAGE_ONLY:True，意味着只用了图像编码。那config文件中的vocab_size=250002的含义是什么呢，是用来做什么的。因为我看它区别于原始layoutlmv3中的大了很多。

**Comment by ouyanglinke** [comment]
我们提供的LayoutLmv3的权重是基于[microsoft/layoutlmv3-base-chinese](https://huggingface.co/microsoft/layoutlmv3-base-chinese)的pretrain模型基础上微调的，config.json文件跟[layoutlmv3-base-chinese模型的config.json](https://huggingface.co/microsoft/layoutlmv3-base-chinese/blob/main/config.json)保持一致。

**Comment by ai1361720220000** [comment]
> 我们提供的LayoutLmv3的权重是基于[microsoft/layoutlmv3-base-chinese](https://huggingface.co/microsoft/layoutlmv3-base-chinese)的pretrain模型基础上微调的，config.json文件跟[layoutlmv3-base-chinese模型的config.json](https://huggingface.co/microsoft/layoutlmv3-base-chinese/blob/main/config.json)保持一致。

请问微调的时候有加入ocr的信息吗？还是像layoutlmv3那样只用图像部分，没有用ocr部分，直接做一个检测就可以

**Comment by ouyanglinke** [comment]
检测的时候没有OCR信息引入，微调用的是LayoutLmv3提供的[Object Detection]部分代码(https://github.com/microsoft/unilm/tree/master/layoutlmv3/examples/object_detection)。
