### ISSUE TITLE
生成的json文件如何解析。

### ISSUE THREAD

**Issue by ttkrpink** [opendatalab/PDF-Extract-Kit#27]
生成的json文件如果按顺序打印text部分，文字的段落是错的。

比如PDF是扫描的书籍，段落顺序是ABC。json虽然是每行一个json元素，一段话前后都在一起。但是段落的顺序错了，变成了ACB，比如说。json里面哪个键值是表示文字的位置的？

**Comment by myhloli** [comment]
请使用https://github.com/opendatalab/MinerU 进行解析 按教程安装之后，使用命令行magic-pdf pdf-command --pdf "pdf_path" --model "model_json_path"即可解析

**Comment by 3030373635** [comment]
> 请使用https://github.com/opendatalab/MinerU进行解析 按教程安装之后，使用命令行magic-pdf pdf-command --pdf "pdf_path" --model "model_json_path"即可解析

 解析完了，有解析成txt的吗，我看最终是md好像

**Comment by wangbinDL** [comment]
txt并不支持公式等特殊字符及标题，如果需要可以直接Google下，很多markdown转txt工具。
