### ISSUE TITLE
What about Poetry?

### ISSUE THREAD

**Issue by dantetemplar** [opendatalab/PDF-Extract-Kit#32]
It seems that the project may have a dependency problem. Poetry would allow you to freeze dependencies and get a more convenient installation of the module. Moreover, it could be made into a library in PyPI, and not just code as it is.

If you are interested, then I could help you.

**Comment by wangbinDL** [comment]
Thank you for your suggestion regarding the use of Poetry to manage dependencies and improve the installation process. We agree that transitioning to Poetry could significantly enhance the user experience by stabilizing our dependency management. We are keen on optimizing this aspect and would greatly appreciate your collaboration in this effort.

Please feel free to join our [Discord](https://discord.gg/AsQMhuMN) or [WeChat](https://r.vansin.top/?r=MinerU) group to further discuss and contribute to the improvement of the tool. Your expertise and input would be invaluable as we continue to develop and refine PDF-Extract-Kit.
