### ISSUE TITLE
 No such file or directory: 'models\MFD\weights.pt'

### ISSUE THREAD

**Issue by mickeyyeung** [opendatalab/PDF-Extract-Kit#33]
Everything was set up correctly, but when I ran the program, it showed an error: FileNotFoundError: [Errno 2] No such file or directory: 'models\MFD\weights.pt'. How can I fix this problem?

Win 11

**Comment by IeohMingChan** [comment]
hello, how to fix it?

**Comment by Zxy1414** [comment]
我也有这个问题

**Comment by wangbinDL** [comment]
Download the model as instructed in the README and place it in the correct directory. Then, try running the program again.
