### ISSUE TITLE
可以在colab上运行吗

### ISSUE THREAD

**Issue by tytung2020** [opendatalab/PDF-Extract-Kit#36]
想先试一试，但是不想安装在本地。希望能有个支持colab的代码 谢谢

**Comment by zhchbin** [comment]
I have developed a simple demo, hoping it will be helpful.

<a target="_blank" href="https://colab.research.google.com/drive/1fClWQXxfOISwN_69LBC1JD42NzMcpZNH?usp=sharing">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

**Comment by tytung2020** [comment]
thanks! will try it out
