### ISSUE TITLE
表格解析问题

### ISSUE THREAD

**Issue by tanlili2025** [opendatalab/PDF-Extract-Kit#45]
你好，看到readme上介绍表格布局检测用的是layoutlmv3，这个是支持表格解析的，但是看到colab笔记本的范例运行的结果表格解析出的是一个图片，请问这个是怎么回事？谢谢！

**Comment by ouyanglinke** [comment]
目前的表格解析还未支持，因此以crop图片的方式保留，表格解析在后续会进行支持，请持续关注！
目前布局检测部分用的是Layoutlmv3的[Object Detection](https://github.com/microsoft/unilm/tree/master/layoutlmv3/examples/object_detection)部分训练的，这部分只用到了视觉信息，具体可以参考[paper](https://arxiv.org/pdf/2204.08387)的Section3.4。

**Comment by ericg108** [comment]
@ouyanglinke 请问有大概支持的时间点吗，表格信息在很多场景比如金融都还挺重要的，谢谢！

**Comment by ouyanglinke** [comment]
表格解析已经支持了，请参考该README进行配置：[StructEqTable](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/demo/TabRec/StructEqTable/README_TABLE.md)。

**Comment by ericg108** [comment]
> 表格解析已经支持了，请参考该README进行配置：[StructEqTable](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/demo/TabRec/StructEqTable/README_TABLE.md)。

看到了，非常感谢！
