### ISSUE TITLE
为啥提示没有 PIL.Image.LINEAR 这个属性？

### ISSUE THREAD

**Issue by ddkk3000** [opendatalab/PDF-Extract-Kit#47]
我程序运行的错误如下，使用的是cpu模式，cpu是intel12490。

Traceback (most recent call last):
  File "D:\PDF-Extract-Kit-main\pdf_extract.py", line 24, in <module>
    from modules.layoutlmv3.model_init import Layoutlmv3_Predictor
  File "D:\PDF-Extract-Kit-main\modules\layoutlmv3\model_init.py", line 1, in <module>
    from .visualizer import Visualizer
  File "D:\PDF-Extract-Kit-main\modules\layoutlmv3\visualizer.py", line 16, in <module>
    from detectron2.data import MetadataCatalog
  File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\detectron2\data\__init__.py", line 2, in <module>
    from . import transforms  # isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\detectron2\data\transforms\__init__.py", line 4, in <module>
    from .transform import *
  File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\detectron2\data\transforms\transform.py", line 36, in <module>
    class ExtentTransform(Transform):
  File "C:\Users\lixiaozhe\AppData\Local\Programs\Python\Python311\Lib\site-packages\detectron2\data\transforms\transform.py", line 46, in ExtentTransform
    def __init__(self, src_rect, output_size, interp=Image.LINEAR, fill=0):
                                                     ^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'LINEAR'. Did you mean: 'BILINEAR'?

**Comment by myhloli** [comment]
detectron2的版本有点老，不兼容新版本的pillow库

**Comment by aceliuchanghong** [comment]
pip install pillow==8.4.0

**Comment by thethepai** [comment]
detectron2版本太旧了，删除后重新安装：

pip uninstall detectron2
git clone https://github.com/facebookresearch/detectron2.git
python -m pip install -e detectron2

**Comment by ddkk3000** [comment]
命令执行有问题。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Jul 24, 2024 10:48 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [opendatalab/PDF-Extract-Kit] 为啥提示没有 PIL.Image.LINEAR 这个属性？ (Issue #47)

&nbsp;



 
detectron2版本太旧了，删除后重新安装：
 
pip uninstall detectron2
 git clone https://github.com/facebookresearch/detectron2.git
 python -m pip install -e detectron2

**Comment by ddkk3000** [comment]
> detectron2版本太旧了，删除后重新安装，步骤如下：
> 
> pip uninstall detectron2 git clone https://github.com/facebookresearch/detectron2.git python -m pip install -e detectron2

错误如下。应该就是你说的错误。

**Comment by ddkk3000** [comment]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\cassert(9): fatal error C1083: 无法打开包括文件: “assert.h”: No such file or directory
    error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ddkk3000** [comment]
> pip install pillow==8.4.0

这个命令也执行不下去。错误是：C:\Users\lixiaozhe\AppData\Local\Temp\pip-install-e0sfqo6s\pillow_5cda8160eaef45e8ac3211eb59bd5943\setup.py:46: RuntimeWarning: Pillow 8.4.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pillow)

**Comment by ddkk3000** [comment]
谢谢，这次可以了，只是cpu太慢了，一个很小的pdf文件半小时了还没抽取完。我没看清楚，原来需要装ImageMagick。&nbsp;
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaomeng&nbsp;Zhao"; 
发送时间: 2024年7月24日(星期三) 晚上7:19
收件人: "opendatalab/PDF-Extract-Kit"; 
抄送: "ddkk3000"; "Author"; 
主题: Re: [opendatalab/PDF-Extract-Kit] 为啥提示没有 PIL.Image.LINEAR 这个属性？ (Issue #47)

&nbsp;



 
windows请参考这个文档进行安装
 
https://github.com/opendatalab/PDF-Extract-Kit/blob/main/docs/Install_in_Windows_zh_cn.md
 
&mdash;
