### ISSUE TITLE
无法找到fairscale

### ISSUE THREAD

**Issue by WillingLau** [opendatalab/PDF-Extract-Kit#50]
已经pip install fairscale又卸载重新安装了，还更新了pip工具，又重新安装了，一直报这个错，其他环境基本已经配好，但是我估计是版本不兼容，虽然pip check也没显示出来不兼容的包，请作者出一个完整的requirements呗，目前是windows

**Comment by Noobility** [comment]
我也遇到了这个问题，我手动在venv里重新安装fairscale以后就可以了，要注意使用`--no-cache-dir`来避免使用缓存
```bash
pip uninstall fairscale
pip install --no-cache-dir fairscale
```
