### ISSUE TITLE
window10运行时报错FileNotFoundError: [Errno 2] No such file or directory: 'models\\MFD\\weights.pt

### ISSUE THREAD

**Issue by freedom1993** [opendatalab/PDF-Extract-Kit#51]
![image](https://github.com/user-attachments/assets/b8b4832b-9cea-4901-8a7e-358f05d58888)

**Comment by ouyanglinke** [comment]
请修改[配置文件](~/PDF-Extract-Kit/configs/model_configs.yaml)里的各个模型权重的路径为你的本地下载好的模型的权重路径。

**Comment by freedom1993** [comment]
意思是涉及的模型文件我都得自己先下载到本地吗
![image](https://github.com/user-attachments/assets/a971e268-717f-4e26-9655-4f2f002fcb95)

**Comment by freedom1993** [comment]
解决了，多谢

**Comment by freedom1993** [comment]
fix
