### ISSUE TITLE
Environmental issues 环境问题 

### ISSUE THREAD

**Issue by vincent-cj** [opendatalab/PDF-Extract-Kit#52]
项目要求python=3.10，但是依赖的detectron2，却只支持很老的torch版本，对应的torch版本不支持python3.10，官方给的detectron2安装命令为：```python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html```
The project requires python=3.10, but the dependent detectron2 only supports very old torch versions. The corresponding torch version does not support python3.10. The official install command for detectron2 is: python -m pip install detectron2 -f https ://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/index.html````

**Comment by myhloli** [comment]
用预编译的版本就可以了

pip install detectron2 --extra-index-url https://myhloli.github.io/wheels/
