### ISSUE TITLE
You probably had not installed ImageMagick library

### ISSUE THREAD

**Issue by HANCHIE** [opendatalab/PDF-Extract-Kit#59]
mac上已经安装了相关库，但是还是报错

**Comment by HANCHIE** [comment]
<img width="674" alt="image" src="https://github.com/user-attachments/assets/8b200fc7-9822-4616-96f3-ebf53ee790a1">
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/9185a5ec-8a91-4e29-83de-7b69957b59fd">

**Comment by ice7li** [comment]
我也遇到这个问题了，请问如何解决的呀？
