### ISSUE TITLE
hugging face上重新下载的 layoutlmv3-base-chinese的权重没法用，命名完全不一样....

### ISSUE THREAD

**Issue by sheng49** [opendatalab/PDF-Extract-Kit#65]
WARNING [07/31 17:14:22 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
backbone.bottom_up.backbone.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.fpn1.0.{bias, weight}
backbone.bottom_up.backbone.encoder.fpn1.1.{bias, running_mean, running_var, weight}
backbone.bottom_up.backbone.encoder.fpn1.3.{bias, weight}
backbone.bottom_up.backbone.encoder.fpn2.0.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.0.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.1.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.10.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.11.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.2.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.3.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.4.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.5.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.6.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.7.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.8.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.attention.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.attention.output.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.attention.self.key.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.attention.self.query.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.attention.self.value.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.intermediate.dense.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.output.LayerNorm.{bias, weight}
backbone.bottom_up.backbone.encoder.layer.9.output.dense.{bias, weight}
backbone.bottom_up.backbone.norm.{bias, weight}
backbone.bottom_up.backbone.patch_embed.proj.{bias, weight}
backbone.bottom_up.backbone.{cls_token, pos_embed}
backbone.fpn_lateral2.{bias, weight}
backbone.fpn_lateral3.{bias, weight}
backbone.fpn_lateral4.{bias, weight}
backbone.fpn_lateral5.{bias, weight}
backbone.fpn_output2.{bias, weight}
backbone.fpn_output3.{bias, weight}
backbone.fpn_output4.{bias, weight}
backbone.fpn_output5.{bias, weight}
proposal_generator.rpn_head.anchor_deltas.{bias, weight}
proposal_generator.rpn_head.conv.{bias, weight}
proposal_generator.rpn_head.objectness_logits.{bias, weight}
roi_heads.box_head.0.fc1.{bias, weight}
roi_heads.box_head.0.fc2.{bias, weight}
roi_heads.box_head.1.fc1.{bias, weight}
roi_heads.box_head.1.fc2.{bias, weight}
roi_heads.box_head.2.fc1.{bias, weight}
roi_heads.box_head.2.fc2.{bias, weight}
roi_heads.box_predictor.0.bbox_pred.{bias, weight}
roi_heads.box_predictor.0.cls_score.{bias, weight}
roi_heads.box_predictor.1.bbox_pred.{bias, weight}
roi_heads.box_predictor.1.cls_score.{bias, weight}
roi_heads.box_predictor.2.bbox_pred.{bias, weight}
roi_heads.box_predictor.2.cls_score.{bias, weight}
roi_heads.mask_head.deconv.{bias, weight}
roi_heads.mask_head.mask_fcn1.{bias, weight}
roi_heads.mask_head.mask_fcn2.{bias, weight}
roi_heads.mask_head.mask_fcn3.{bias, weight}
roi_heads.mask_head.mask_fcn4.{bias, weight}
roi_heads.mask_head.predictor.{bias, weight}
WARNING [07/31 17:14:22 fvcore.common.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  layoutlmv3.{cls_token, pos_embed}
  layoutlmv3.embeddings.position_ids
  layoutlmv3.embeddings.word_embeddings.weight
  layoutlmv3.embeddings.token_type_embeddings.weight
  layoutlmv3.embeddings.LayerNorm.{bias, weight}
  layoutlmv3.embeddings.position_embeddings.weight
  layoutlmv3.embeddings.x_position_embeddings.weight
  layoutlmv3.embeddings.y_position_embeddings.weight
  layoutlmv3.embeddings.h_position_embeddings.weight
  layoutlmv3.embeddings.w_position_embeddings.weight
  layoutlmv3.encoder.layer.0.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.0.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.0.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.0.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.0.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.0.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.0.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.0.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.1.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.1.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.1.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.1.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.1.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.1.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.1.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.1.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.2.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.2.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.2.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.2.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.2.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.2.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.2.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.2.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.3.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.3.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.3.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.3.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.3.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.3.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.3.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.3.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.4.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.4.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.4.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.4.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.4.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.4.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.4.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.4.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.5.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.5.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.5.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.5.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.5.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.5.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.5.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.5.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.6.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.6.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.6.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.6.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.6.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.6.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.6.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.6.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.7.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.7.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.7.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.7.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.7.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.7.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.7.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.7.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.8.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.8.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.8.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.8.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.8.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.8.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.8.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.8.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.9.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.9.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.9.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.9.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.9.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.9.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.9.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.9.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.10.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.10.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.10.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.10.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.10.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.10.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.10.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.10.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.11.attention.self.query.{bias, weight}
  layoutlmv3.encoder.layer.11.attention.self.key.{bias, weight}
  layoutlmv3.encoder.layer.11.attention.self.value.{bias, weight}
  layoutlmv3.encoder.layer.11.attention.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.11.attention.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.layer.11.intermediate.dense.{bias, weight}
  layoutlmv3.encoder.layer.11.output.dense.{bias, weight}
  layoutlmv3.encoder.layer.11.output.LayerNorm.{bias, weight}
  layoutlmv3.encoder.rel_pos_bias.weight
  layoutlmv3.encoder.rel_pos_x_bias.weight
  layoutlmv3.encoder.rel_pos_y_bias.weight
  layoutlmv3.patch_embed.proj.{bias, weight}
  layoutlmv3.LayerNorm.{bias, weight}
  layoutlmv3.norm.{bias, weight}

**Comment by wangbinDL** [comment]
Please make sure to use the fine-tuned weights we provide. You can find them at the following link:

[https://huggingface.co/wanderkid/PDF-Extract-Kit/tree/main/models/Layout](https://huggingface.co/wanderkid/PDF-Extract-Kit/tree/main/models/Layout)
