### ISSUE TITLE
paddlepaddle-gpu

### ISSUE THREAD

**Issue by randydl** [opendatalab/PDF-Extract-Kit#7]
paddlepaddle-gpu在pypi页面上写的pypi源只支持cuda 10.2，内容如下：

specific version cuda:
We only release paddlepaddle-gpu cuda10.2 on pypi.

If you want to install paddlepaddle-gpu with cuda version of 10.2/11.2/11.6/11.7, commands to install are on our website: [Installation Document](https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/frompip_en.html)

但是我看到咱们这边的安装环境应该是cuda 12.1，所以requirements.txt里面直接写paddlepaddle-gpu是不是不对呀？

**Comment by wufan-tb** [comment]
我们按教程里的流程走过，应该没有问题，可能paddle其他的模型对cuda的版本有要求，paddleocr对cuda没有明确的版本要求
