### ISSUE TITLE
layout部分有训练代码吗 还是说用微软官方的？

### ISSUE THREAD

**Issue by lawliet1777** [opendatalab/PDF-Extract-Kit#73]

**Comment by ouyanglinke** [comment]
训练代码用的是LayoutLmv3的[object Detection](https://github.com/microsoft/unilm/tree/master/layoutlmv3/examples/object_detection)部分。

**Comment by lawliet1777** [comment]
> 训练代码用的是LayoutLmv3的[object Detection](https://github.com/microsoft/unilm/tree/master/layoutlmv3/examples/object_detection)部分。

是要参考LayoutLmv3在PubLayNet数据集上微调的例子吗  也就是说要把训练数据转化成PubLayNet数据集的格式

**Comment by ouyanglinke** [comment]
是的，运行的命令在其官方[README](https://github.com/microsoft/unilm/tree/master/layoutlmv3#document-layout-analysis-on-publaynet)可以找到，数据集用的是COCO格式。
