### ISSUE TITLE
关于StructEqTable for table recognition;

### ISSUE THREAD

**Issue by cookieswolf** [opendatalab/PDF-Extract-Kit#75]
很高兴看到表格解析的功能增加上了。但是有个疑问。我运行pdf-extract-kit的colab版本，与之前没有区别。并没有看到把表格，转成图片，然后再解析出来的过程。
![1722689140080](https://github.com/user-attachments/assets/3ff42687-6002-4606-b166-e815c2f23f13)
还是我没有看对地方。请指出谢谢。

还有一个问题，布局检测，我发现对于段落的的识别有问题。我附上了我的pdf文件以及截图。而360LayoutAnalysis-Paper不会出这个问题。
![1722689499443](https://github.com/user-attachments/assets/afeb23ad-06f6-4a31-a4e8-8cdd4aec6e6d)

[llama2_page8.pdf](https://github.com/user-attachments/files/16480650/llama2_page8.pdf)
请查证。谢谢。

**Comment by ouyanglinke** [comment]
Colab上暂时还没有更新，可以先根据[README](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/demo/TabRec/StructEqTable/README_TABLE.md)配置。
另外，关于布局检测，直接用Layout模型是有这一行的结果的，在model.json的结果里应该能够看见。你上面贴的图应该是MinerU后处理过的可视化结果，应该是后处理的某一个步骤筛掉了（下图是Layout模型的结果）。请@myhloli看一下。
![image](https://github.com/user-attachments/assets/928cf423-2d83-48c8-8638-5333072525f4)

**Comment by cookieswolf** [comment]
非常感谢。
另外还有一个不情之请，就是在发布新版的同时，希望能优先有一个完整的示例，能帮助我们快速的了解新版的特性。谢谢。

**Comment by myhloli** [comment]
> Colab上暂时还没有更新，可以先根据[README](https://github.com/opendatalab/PDF-Extract-Kit/blob/main/demo/TabRec/StructEqTable/README_TABLE.md)配置。 另外，关于布局检测，直接用Layout模型是有这一行的结果的，在model.json的结果里应该能够看见。你上面贴的图应该是MinerU后处理过的可视化结果，应该是后处理的某一个步骤筛掉了（下图是Layout模型的结果）。请@myhloli看一下。 ![image](https://private-user-images.githubusercontent.com/113978928/355660090-928cf423-2d83-48c8-8638-5333072525f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjE2MTEsIm5iZiI6MTcyMzAyMTMxMSwicGF0aCI6Ii8xMTM5Nzg5MjgvMzU1NjYwMDkwLTkyOGNmNDIzLTJkODMtNDhjOC04NjM4LTUzMzMwNzI1MjVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwOTAxNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWE5ZmFjNjZmYTNmYmJiNjYzM2YyNzc2YTdhMDhjMGViNGQzMjM0NzZiN2U1NTc2ODRjZDExZWJhMmUzYTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mcbBLoiJy3SrthXg1T8dP6nWdJjGd5bZ6hKfkjUFhk4)

我们目前的逻辑一个table只会有一个table caption块可以跟table body相关联，在这个例子中，一个table body 上下各出现了一个 table caption，算法根据最近原则，采用了下方的table caption和table body合并成了一个table block。因此，上方的table caption被丢弃了。
