### ISSUE TITLE
AttributeError: 'CustomMBartDecoder' object has no attribute 'embed_scale'出现这个报错

### ISSUE THREAD

**Issue by SidneyRey** [opendatalab/PDF-Extract-Kit#85]
你好，感谢分享代码！
我在运行时报错：
conda/envs/marker/lib/python3.10/site-packages/unimernet/models/unimernet/encoder_decoder.py", line 235, in forward
    inputs_embeds = self.embed_tokens(input_ids) * self.embed_scale
conda/envs/marker/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CustomMBartDecoder' object has no attribute 'embed_scale'
是版本问题吗？

**Comment by wangbinDL** [comment]
Check the response here: [https://github.com/opendatalab/UniMERNet/issues/10](https://github.com/opendatalab/UniMERNet/issues/10)
