### ISSUE TITLE
对于扫描类PDF文档，plain text和ocr text会反复标记，造成识别重复

### ISSUE THREAD

**Issue by xeon-ye** [opendatalab/PDF-Extract-Kit#9]
如上

**Comment by myhloli** [comment]
plaintext是块级别的文本区域，ocrtext是line或者span级别的文本区域，后端处理解析结果的时候可以自行选择是否采用ocr的文本信息或者通过api提取pdf中的文本，具体的后端处理逻辑可以参考mineru项目

**Comment by xeon-ye** [comment]
thx,got it!
